# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ghidra_llm_pb2 as ghidra__llm__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ghidra_llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GhidraLLMStub(object):
    """Service definition for Ghidra LLM integration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryLLM = channel.unary_unary(
                '/ghidra.llm.GhidraLLM/QueryLLM',
                request_serializer=ghidra__llm__pb2.QueryRequest.SerializeToString,
                response_deserializer=ghidra__llm__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.AnalyzeBinary = channel.unary_unary(
                '/ghidra.llm.GhidraLLM/AnalyzeBinary',
                request_serializer=ghidra__llm__pb2.BinaryAnalysisRequest.SerializeToString,
                response_deserializer=ghidra__llm__pb2.BinaryAnalysisResponse.FromString,
                _registered_method=True)
        self.ExplainCode = channel.unary_unary(
                '/ghidra.llm.GhidraLLM/ExplainCode',
                request_serializer=ghidra__llm__pb2.CodeExplanationRequest.SerializeToString,
                response_deserializer=ghidra__llm__pb2.CodeExplanationResponse.FromString,
                _registered_method=True)
        self.SuggestAnalysis = channel.unary_unary(
                '/ghidra.llm.GhidraLLM/SuggestAnalysis',
                request_serializer=ghidra__llm__pb2.AnalysisSuggestionRequest.SerializeToString,
                response_deserializer=ghidra__llm__pb2.AnalysisSuggestionResponse.FromString,
                _registered_method=True)


class GhidraLLMServicer(object):
    """Service definition for Ghidra LLM integration
    """

    def QueryLLM(self, request, context):
        """Generate a response from the LLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBinary(self, request, context):
        """Analyze a binary file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainCode(self, request, context):
        """Explain code or assembly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestAnalysis(self, request, context):
        """Suggest next analysis steps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GhidraLLMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLLM,
                    request_deserializer=ghidra__llm__pb2.QueryRequest.FromString,
                    response_serializer=ghidra__llm__pb2.QueryResponse.SerializeToString,
            ),
            'AnalyzeBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBinary,
                    request_deserializer=ghidra__llm__pb2.BinaryAnalysisRequest.FromString,
                    response_serializer=ghidra__llm__pb2.BinaryAnalysisResponse.SerializeToString,
            ),
            'ExplainCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainCode,
                    request_deserializer=ghidra__llm__pb2.CodeExplanationRequest.FromString,
                    response_serializer=ghidra__llm__pb2.CodeExplanationResponse.SerializeToString,
            ),
            'SuggestAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestAnalysis,
                    request_deserializer=ghidra__llm__pb2.AnalysisSuggestionRequest.FromString,
                    response_serializer=ghidra__llm__pb2.AnalysisSuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ghidra.llm.GhidraLLM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ghidra.llm.GhidraLLM', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GhidraLLM(object):
    """Service definition for Ghidra LLM integration
    """

    @staticmethod
    def QueryLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghidra.llm.GhidraLLM/QueryLLM',
            ghidra__llm__pb2.QueryRequest.SerializeToString,
            ghidra__llm__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghidra.llm.GhidraLLM/AnalyzeBinary',
            ghidra__llm__pb2.BinaryAnalysisRequest.SerializeToString,
            ghidra__llm__pb2.BinaryAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghidra.llm.GhidraLLM/ExplainCode',
            ghidra__llm__pb2.CodeExplanationRequest.SerializeToString,
            ghidra__llm__pb2.CodeExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghidra.llm.GhidraLLM/SuggestAnalysis',
            ghidra__llm__pb2.AnalysisSuggestionRequest.SerializeToString,
            ghidra__llm__pb2.AnalysisSuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
